# Generated by Django 4.1 on 2023-01-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('etiqueta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiquetas.etiqueta', verbose_name='Etiqueta')),
            ],
        ),
    ]
